### ISSUE TITLE
Build fails w/ Astro 5 + Vue + Cloudflare 

### ISSUE THREAD

**Issue by Uninen** [withastro/adapters#470]
### Astro Info

```block
Astro                    v5.0.3
Node                     v20.13.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/vue
```

### Describe the Bug

`astro build` fails with following error when project has Vue integration and Cloudflare adapter installed:

```
23:54:56 [ERROR] [vite] x Build failed in 97ms
[commonjs--resolver] [plugin vite:resolve] Cannot bundle Node.js built-in "node:stream" imported from "node_modules/.pnpm/@vue+server-renderer@3.5.13_vue@3.5.13_typescript@5.7.2_/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js". Consider disabling environments.ssr.noExternal or remove the built-in dependency.
file: /Users/uninen/Code/Temp/cf-test/node_modules/.pnpm/@vue+server-renderer@3.5.13_vue@3.5.13_typescript@5.7.2_/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js
  Stack trace:
    at getRollupError (file:///Users/uninen/Code/Temp/cf-test/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
    at Object.error (file:///Users/uninen/Code/Temp/cf-test/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:20627:20)
    at Object.handler (file:///Users/uninen/Code/Temp/cf-test/node_modules/.pnpm/vite@6.0.3_@types+node@22.10.1/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:50806:15)
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/uninen/Code/Temp/cf-test/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:20712:28)
    at async ModuleLoader.resolveId (file:///Users/uninen/Code/Temp/cf-test/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:19745:15)
 ELIFECYCLE  Command failed with exit code 1.
```

Steps to repro:

1. pnpm create astro@latest 
2. pnpm astro add vue 
3. pnpm astro add cloudflare  
4. pnpm build

(See the attached repro project)

### What's the expected result?

Build succeeds

### Link to Minimal Reproducible Example

https://github.com/Uninen/astro5-vue-cloudflare-issue

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment]
This is a known limitation of Cloudflare, we do have docs on how to avoid this error: https://docs.astro.build/en/guides/integrations-guide/cloudflare/#nodejs-compatibility

**Comment by Uninen** [comment]
Not sure what that means. This setup worked well w/ Astro v4 but doesn't anymore w/ v5. 

Does "known limitation" mean that `@astrojs/vue` is incompatible with Cloudflare adapter? Ie. it's not supposed to work with it? Or does it mean that "it might or might not work if you exclude right Node APIs in your Vite config"? (I mean, sure, it's easy to exclude `node:stream` now and it indeed works in the repro, but what happens if/when `@astrojs/vue` changes something internally in a way where excluding doesn't help anymore?)

Note that the code is not using any Node APIs nor Cloudflare workers here, and in fact the example is not using any features at all!

I'm just trying to understand if I should invest any time in building something with this adapter together with `@astrojs/vue` in the same project. I guess my confusion is that these are first-party addons and there's no documentation about possible issues when using them together. And as long as it's _my_ code that I can control, I'm 100% happy to adhere to any limitations like this :)

**Comment by ematipico** [comment]
The package `@vue/server-renderer` uses `node:stream`, that's why it fails. Even if your code doesn't use any Node.js APIs, some of your deps do.

I don't know why that worked before, but breaking changes are expected.

**Comment by thomas-callahan-collibra** [comment]
This can't be right. In order to get my build working in an Astro 5 update test branch I started adding these built-ins to `vite.ssr.external` as listed on the instructions page above. (I had nothing in this config before). Because the build fails on the first one, I had to add these one at a time as each subsequent build failed. I got to around 20 of them listed, finally gave up, and as a last ditch effort looked up a list of Node's built-ins and added them **all** with the `node:` prefix since that's how they were all being reported in the build failures Yes I know this is ridiculous but I just wanted to see if it was even possible to get this working.

Then it failed on due to an _unprefixed_ version of one of those, so I added them all a second time without the `node:` prefix and the build finally got to the point where it was rendering pages. So, _progress_, but I now have 108 items in this list.

And now after it finishes building pages, CloudFlare reports that the assets are uploaded, but then the build fails in the very last step trying to deploy a function (we have two Astro "dynamic endpoints" opted out of prerendering), again due to a Node `node:stream` issue. And if I remove `node:stream` from `vite.ssr.external` it goes back to failing at the start.

![image](https://github.com/user-attachments/assets/bc1d0c42-af3b-40b1-a7a7-e3f2e4f53722)

```
  vite: {
    ssr: {
      external: [
        "node:assert",
        "node:assert/strict",
        "node:async_hooks",
        "node:buffer",
        "node:child_process",
        "node:cluster",
        "node:console",
        "node:constants",
        "node:crypto",
        "node:dgram",
        "node:diagnostics_channel",
        "node:dns",
        "node:dns/promises",
        "node:domain",
        "node:events",
        "node:fs",
        "node:fs/promises",
        "node:http",
        "node:http2",
        "node:https",
        "node:inspector",
        "node:inspector/promises",
        "node:module",
        "node:net",
        "node:os",
        "node:path",
        "node:path/posix",
        "node:path/win32",
        "node:perf_hooks",
        "node:process",
        "node:punycode",
        "node:querystring",
        "node:readline",
        "node:readline/promises",
        "node:repl",
        "node:stream",
        "node:stream/consumers",
        "node:stream/promises",
        "node:stream/web",
        "node:string_decoder",
        "node:timers",
        "node:timers/promises",
        "node:tls",
        "node:trace_events",
        "node:tty",
        "node:url",
        "node:util",
        "node:util/types",
        "node:v8",
        "node:vm",
        "node:wasi",
        "node:worker_threads",
        "node:zlib",
        "assert",
        "assert/strict",
        "async_hooks",
        "buffer",
        "child_process",
        "cluster",
        "console",
        "constants",
        "crypto",
        "dgram",
        "diagnostics_channel",
        "dns",
        "dns/promises",
        "domain",
        "events",
        "fs",
        "fs/promises",
        "http",
        "http2",
        "https",
        "inspector",
        "inspector/promises",
        "module",
        "net",
        "os",
        "path",
        "path/posix",
        "path/win32",
        "perf_hooks",
        "process",
        "punycode",
        "querystring",
        "readline",
        "readline/promises",
        "repl",
        "stream",
        "stream/consumers",
        "stream/promises",
        "stream/web",
        "string_decoder",
        "timers",
        "timers/promises",
        "tls",
        "trace_events",
        "tty",
        "url",
        "util",
        "util/types",
        "v8",
        "vm",
        "wasi",
        "worker_threads",
        "zlib",
      ],
    },
  },
  ```

**Comment by alexanderniebuhr** [comment]
The behavior of adding the node APIs as external dependencies is not new. It was in place in v4. I don't know why it worked before, but I think maybe a third party library got an update too, and now is not compatible anymore. I do suggest checking if there is anything related

**Comment by alexanderniebuhr** [comment]
@hi-ogawa thanks for adding this information. I'm pretty sure @bluwy added that options to workaround another issue in vite. 🤔

I would like to understand if we should revert that change or what the best approach is now?

**Comment by bluwy** [comment]
The best approach is what I mentioned on discord: https://discord.com/channels/830184174198718474/845430950191038464/1315057526877716512

**Comment by lassegit** [comment]
Build fails regardless of using `@vue/server-renderer`.

**Comment by thomascallahan** [comment]
I found a solution. Above, as @thomas-callahan-collibra  (which is my company account) I had tried adding numerous packages to `vite.ssr.external` with no luck.  Yesterday I tried the same upgrade with a personal project hoping it would go more smoothly since it's a much simpler site. It didn't.

I haven't tested this with my company's project yet, but the setup is essentially identical so I expect it will work.

To fix this, add a `wrangler.toml` to your Pages project. Doing this is listed as "experimental" by CloudFlare, but it works. In it, you need to have at least 3 items. Ideally you're supposed to treat this file as the source of truth for your project's config, but I've found several issues with it, so I just put in the bare minimum and still rely on the dashboard for most other things:

```
name = "name-of-your-project"
pages_build_output_dir = "./dist"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat_v2"]
```
(`compatibility_date` _may_ be optional -- set it to something later than September, 2024 to get the latest Node compatibility layer)

This makes the Worker that builds your Pages project use CloudFlare's updated Node compatibility layer, and you don't need to have a Vite object in your Astro config at all, it just works out of the box. 

Given the pending PR above, this may not be necessary once that's merged, but I don't know that it's a bad idea to do both -- there are other benefits to running the compatibility layer, like I know my company's project had something that wanted `node:crypto` and we switched to a pure JS package, we could probably switch back.

You CAN also set this compatibility flag in the CloudFlare Dashboard, but it's not actually listed in the dropdown options, you need to enter it manually, and you need to use `nodejs_compat` not `nodejs_compat_v2` (although according to CloudFlare, as of September 2024 they're both the same). BUT you need to have a `wrangler.toml` in order for this to have any effect anyway, so you might as well just specify it in the file.

The only other issue is that if your project has a `wrangler.toml`, the `NODE_VERSION` environment variable you may have set in your dashboard has no effect. All of your other vars will be fine, it's just that one that is ignored. The solution to that, assuming you want or need to set a Node version, is to add a `.nvmrc` file to your project, with the contents being whatever version you want, i.e. `20`.

Final note , I was getting peer dependency warnings when running `npm install`. Nothing was broken, but v 12.0.1 of the CloudFlare Pages adapter depends on `@inoxtools/astro-when` v0.24 which depends on Astro 4. `astro-when` was updated with Astro 5/Vite 6 support a few days ago. Adding an overrides object to your `package.json` forcing `astro-when` to the latest fixes the warnings. Again either way everything appears to work but if you don't like warnings, it doesn't seem to hurt to force it.

  ```
  "overrides": {
    "@inox-tools/astro-when": "1.0.1"
  }
```

**Comment by thomas-callahan-collibra** [comment]
Correction to the post above -- environment variables DO need to be migrated to `wrangler.toml` in order to make this work. The small project I tried it with only had one and it wasn't used in a way that would have failed the bid. On a larger project the build fails due to `astro:env` validation finding missing vars.

**Comment by thomas-callahan-collibra** [comment]
Correction, again -- the workaround above only worked for a small project not using server-side Vue rendering via Astro at all. I forgot that that project was doing it purely client-side (not even using Astro's `client:` directives -- this is literally just JS calling Vue's `createApp`). In my larger project with server-side rendering and Astro `client:` directives, it still fails.

**Comment by evadecker** [comment]
I'm running into this issue with the Cloudflare adapter as well. I'm not using Vue, but I think #476 will fix the issue.
